/* DO NOT EDIT, file generated by nestjs-i18n */
  
/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "emailUpdatedEmail": {
        "greeting": string;
        "message": string;
        "login": string;
    };
    "inviteEmail": {
        "greeting": string;
        "assignMessage": string;
        "assignMessageWithoutOrgLogo": string;
        "assignMessageWithoutOrg": string;
        "email": string;
        "password": string;
        "changePassword": string;
        "login": string;
        "ignoreIt": string;
        "welcomeAboard": string;
        "hopeCloudTeam": string;
    };
    "resetPasswordEmail": {
        "title": string;
        "resetYourPassword": string;
        "buttonText": string;
        "ignoreIt": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
