version: "3"

services:
  db:
    image: postgres:14-alpine
    container_name: nestkit_starter_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nestkit_starter
    ports:
      - "5423:5432"
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    networks:
      - private

networks:
  private:
    driver: bridge
